# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: OTRmMDU3MzA4MTY1MzcwMDBkMjk0ZDdhOTA4ZDZhNDRlMDc1ZWZhZGM5YmQwOWUyOTQ2Yjk2ZjJlYmI3NWE0YTc4YzI5OWIyNGI2NmU2MTMzMjZhNjQ0NjEzNzAxOTcxZWUzNzE5Mjg4MzFjMWE4OGZiMDY1MDkwMzFiYzU1NTE=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
